### PR TITLE
Update for aeson-2.2

### PR DESCRIPTION
**Pull request by 9999years**
aeson-2.2 is unreleased right now, but this will be useful in the future

### CODE REVIEW

**Comment by martijnbastiaan** [comment]
Thanks! I'll add some CI to this repo to make sure this doesn't break older `aeson`s.

**Comment by martijnbastiaan** [comment]
Could you rebase on `master` and add the latest `aeson` to CI?

**Comment by 9999years** [comment]
Yeah, ping me whenever aeson-2.2 is released (or someone will find this issue and bump it) and we can get this fixed up and merged.

(For now, we're using it to patch our build internally.)

**Comment by martijnbastiaan** [comment]
@9999years It's been released! Could you rebase?

**Pull request merged**
